services:

    _defaults:
        autowire: true
        autoconfigure: true
        
    Infrastructure\:
        resource: '../../src/Infrastructure'
        exclude:
            - '../../src/DependencyInjection/'
            - '../../src/Infrastructure/Entity/'
            - '../../src/Infrastructure/Kernel.php'

    Infrastructure\Controller\:
        resource: '../../src/Infrastructure/Controller/'
        tags: ['controller.service_arguments']
